# Jargon busting {-#jargon-busting}

Before we start any technical work, let's start by establishing some terms as a group. The first barrier to getting involved with computational work is often the language barrier -- there are unknown terms and intimidating commands that can be hard to overcome.

So we are going to start with an exercise to get us thinking about data and code from a terminology level! Let's address head-on the terms that give us anxiety and the terms that we are interested in knowing more about, and bust that jargon before the rest of the sessions.

So for this first 30-40min of the day:

1. We will put you into breakout rooms of 4-6.
2. Brainstorm for 5 minutes about any terms, phrases, or ideas around data or code in libraries that you've come across and wish to know better. Just rapid-fire list out terms. Some examples might be, "the terminal," "Git," or "regular expressions."
3. Add your list of all the terms, phrases, and ideas that your group came up with to our class jamboard: https://jamboard.google.com/d/1-F6PKusN8esa9zoPBM4RqAfzsGxk0ADVRLc8QFKP7gg/edit?usp=sharing. If multiple people in your group said the same thing, note that!
    - Use the "board" with the same number as your breakout group, so breakout room 2 goes to board 2/5, breakout room 3 goes to board 3/5, using the arrows at the top of the jamboard. 
4. After your brainstorming session, spend 10 minutes working together to try to explain what the terms, phrases, or ideas on your list mean. Write your potential definitions with your terms on your jamboard. Note: use both each other and the Internet as a resource.
5. Then we'll come back together as a group and have folks report out the terms you were able to explain as well as those you are still struggling with
7. For those that folks weren't able to explain, we'll add those to our mega class list and define them in-class together!